apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-blue
spec:
  selector:
    matchLabels:
      color: blue
  template:
    metadata:
      labels:
        color: blue
    spec:
      containers:
        - name: feelody-back
          image: asia-northeast3-docker.pkg.dev/feelody-458710/feelody-backend/feelody:blue
