apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-green
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring
      color: green
  template:
    metadata:
      labels:
        app: spring
        color: green
    spec:
      serviceAccountName: feelody-k8s-sa
      containers:
        - name: feelody-back
          image: asia-northeast3-docker.pkg.dev/feelody-458710/feelody-backend/feelody:green
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 3

