apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring
      color: PLACEHOLDER
  template:
    metadata:
      labels:
        app: spring
        color: PLACEHOLDER
    spec:
      serviceAccountName: feelody-k8s-sa
      containers:
        - name: feelody-back
          image: PLACEHOLDER
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /api/healthz
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 3
