name: Build Gradle And Push Docker Image

on:
  push:
    branches: [ "main" ]

jobs:
  build-gradle:
    runs-on: ubuntu-22.04
    permissions:
      contents: read

    outputs:
      image_tag: ${{ steps.timestamp.outputs.tag }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"

      - name: Give execute permission to Gradle wrapper
        run: chmod +x ./gradlew

      - name: Create GCS Key file
        run: |
          mkdir -p ./src/main/resources
          echo "${{ secrets.GCP_GCS_KEY }}" > ./src/main/resources/storage-key.json

      - name: Build with Gradle
        run: ./gradlew clean build

      - name: Set image tag
        id: timestamp
        run: echo "tag=$(date +%s)" >> $GITHUB_OUTPUT

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: build/libs/feelody-backend-latest.jar

  docker-publish-to-gcp:
    needs: build-gradle
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: build-output

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_AR_KEY }}

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker asia-northeast3-docker.pkg.dev

      - name: Build Docker image
        run: |
          docker build . -t feelody:${{ needs.build-gradle.outputs.image_tag }}

      - name: Tag image for Artifact Registry
        run: |
          docker tag feelody:${{ needs.build-gradle.outputs.image_tag }} \
          asia-northeast3-docker.pkg.dev/feelody-458710/feelody-backend:${{ needs.build-gradle.outputs.image_tag }}

      - name: Push image to Artifact Registry
        run: |
          docker push asia-northeast3-docker.pkg.dev/feelody-458710/feelody-backend:${{ needs.build-gradle.outputs.image_tag }}
