name: Build Gradle And Push Docker Image

on:
  push:
    branches: [ "main" ]

jobs:
  build-gradle:
    runs-on: ubuntu-22.04
    env:
      GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
    permissions:
      contents: read
    outputs:
      image_tag: ${{ steps.image_tag.outputs.tag }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"

      - name: Give execute permission to Gradle wrapper
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew clean build

      - name: Set image tag
        id: image_tag
        run: |
          CURRENT_TAG=$(kubectl get svc feelody-back -o jsonpath='{.spec.selector.color}')

          if [ "$CURRENT_TAG" = "blue" ]; then
            NEXT_TAG="green"
          else
            NEXT_TAG="blue"
          fi

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_AR_KEY }}

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker asia-northeast3-docker.pkg.dev

      - name: Build Docker image
        run: |
          docker build . -t feelody:${{ steps.image_tag.outputs.tag }}

      - name: Tag image for Artifact Registry
        run: |
          docker tag feelody:${{ steps.image_tag.outputs.tag }} \
          asia-northeast3-docker.pkg.dev/feelody-458710/feelody-backend/feelody:${{ steps.image_tag.outputs.tag }}

      - name: Push image to Artifact Registry
        run: |
          docker push asia-northeast3-docker.pkg.dev/feelody-458710/feelody-backend/feelody:${{ steps.image_tag.outputs.tag }}
